### ISSUE TITLE
Start application

### ISSUE THREAD

**Issue by akastrin** [fogbeam/Valmont-F#1]
I wonder how to start the application. In the root directory I execute `grails run-app` but the following error occurs: "Error occurred running Grails CLI"

**Comment by mindcrime** [comment]
Probably a version mismatch.  I just upgraded this app to Grails 3.3.6.  You might try it again now by either having Grails 3.3.6 on your path, or using ./grailsw run-app in the app root directory.

**Comment by mindcrime** [comment]
So much has changed since this was opened, I'm going to go ahead and close this. OP, if you are still having trouble with this, please open a new ticket.  Also note that we now have a Docker image available on Docker Hub which makes it easy to get the service up and running, if you have Docker running.
